name: CI for frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@4bc047a

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check code
        run: |
          bun tsc
          bun biome ci
